apiVersion: v1
kind: Secret
metadata:
  name: tls-dev-secret
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.tls.dev.crt }}
  tls.key: {{ .Values.tls.dev.key }}
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.tls.prod.crt }}
  tls.key: {{ .Values.tls.prod.key }}
type: kubernetes.io/tls