{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
spec:
  tls:
  - secretName: {{ .Values.ingress.tls.devName }}
  - secretName: {{ .Values.ingress.tls.prodName }}
  rules:
  - host: {{ .Values.ingress.devHost }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          # serviceName: {{ .Values.ingress.serviceName }}
          # servicePort: {{ .Values.ingress.servicePort }}
          service:
            name: {{ .Values.ingress.serviceName }} 
            port:
              number: {{ .Values.ingress.servicePort }}
  - host: {{ .Values.ingress.prodHost }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType}}
        backend:
          # serviceName: {{ .Values.ingress.serviceName }}
          # servicePort: {{ .Values.ingress.servicePort }}
          service:
            name: {{ .Values.ingress.serviceName }}
            port:
              number: {{ .Values.ingress.servicePort }}