{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- include "nb2canvas-chart.ingress.annotations" . | nindent 4 }}
spec:
    rules:
    - host: nb2canvas.ucsd.edu
      http:
        paths:
        - backend:
            service:
              name: nbgrader2canvas-service
              port:
                number: 5000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - nb2canvas.ucsd.edu
      secretName: tls-prod-secret
