{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- include "nb2canvas-chart.ingress.annotations" . | nindent 4 }}
spec:
    rules:
    - host: {{ .Values.ingress.devHost }}
      http:
        paths:
        - backend:
            service:
              name: {{ .Values.ingress.serviceName }}
              port:
                number: {{ .Values.ingress.servicePort }}
          path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
    tls:
    - hosts:
      - {{ .Values.ingress.devHost }}
      secretName: {{ .Values.tls.dev.name }}
