apiVersion: v1
kind: Service
metadata:
  name: nbgrader2canvas-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.nb2canvas.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.nb2canvas.port }}