apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image.repo }}:{{ .Values.postgres.image.tag }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        envFrom:
          - secretRef:
              name: postgres-secret
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: start-db
        - mountPath: /var/lib/postgresql/data/pgdata
          name: test
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      - name: start-db
        nfs:
          server: {{ .Values.nfs.server }}
          path: {{ .Values.nfs.path }}nbgrader-canvas-lti-oauth-flask/scripts   