apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc }}
  PGDATA: {{ .Values.PGDATA | b64enc }}