apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.nb2canvas.name }}
  namespace: {{ .Values.namespace.name }}
type: {{ .Values.secret.nb2canvas.type }}
data:
  FLASK_DEBUG: {{ .Values.secret.nb2canvas.data.FLASK_DEBUG | b64enc }}
  FLASK_ENV: {{ .Values.secret.nb2canvas.data.FLASK_ENV | b64enc }}
  DEBUG_METRICS: {{ .Values.secret.nb2canvas.data.DEBUG_METRICS | b64enc }}
  CANVAS_SSO_USERNAME: {{ .Values.secret.nb2canvas.data.CANVAS_SSO_USERNAME | b64enc }}
  CANVAS_SSO_PASSWORD: {{ .Values.secret.nb2canvas.data.CANVAS_SSO_PASSWORD | b64enc }}
  CANVAS_BASE_URL: {{ .Values.secret.nb2canvas.data.CANVAS_BASE_URL | b64enc }}
  OAUTH2_ID: {{ .Values.secret.nb2canvas.data.OAUTH2_ID | b64enc }}
  OAUTH2_KEY: {{ .Values.secret.nb2canvas.data.OAUTH2_KEY | b64enc }}
  OAUTH2_URI: {{ .Values.secret.nb2canvas.data.OAUTH2_URI | b64enc }}
  LTI_CONSUMER_KEY: {{ .Values.secret.nb2canvas.data.LTI_CONSUMER_KEY | b64enc }}
  LTI_SHARED_SECRET: {{ .Values.secret.nb2canvas.data.LTI_SHARED_SECRET | b64enc }}
  SECRET_KEY: {{ .Values.secret.nb2canvas.data.SECRET_KEY | b64enc }}
  DATABASE_URI: {{ .Values.secret.nb2canvas.data.DATABASE_URI | b64enc }}
  SESSION_KEY: {{ .Values.secret.nb2canvas.data.SESSION_KEY | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.postgres.name }}
  namespace: {{ .Values.namespace.name }}
type: {{ .Values.secret.postgres.type }}
data:
  POSTGRES_USER: {{ .Values.secret.postgres.data.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.data.POSTGRES_PASSWORD | b64enc }}
  PGDATA: {{ .Values.secret.postgres.data.PGDATA | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.dev.name }}
  namespace: {{ .Values.namespace.name }}
data:
  tls.crt: {{ .Values.tls.dev.crt }}
  tls.key: {{ .Values.tls.dev.key }}
type: {{ .Values.tls.type }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.prod.name }}
  namespace: {{ .Values.namespace.name }}
data:
  tls.crt: {{ .Values.tls.prod.crt }}
  tls.key: {{ .Values.tls.prod.key }}
type: {{ .Values.tls.type }}