apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nb2canvas.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    {{- include "nb2canvas-chart.nbgrader2canvas.labels" . | nindent 4 }}
  ports:
  - protocol: {{ .Values.service.nb2canvas.protocol }}
    port: {{ .Values.service.nb2canvas.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.postgres.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    {{- include "nb2canvas-chart.postgres.labels" . | nindent 4 }}
  ports:
  - protocol: {{ .Values.service.postgres.protocol }}
    port: {{ .Values.service.postgres.port }}