version: "2"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    depends_on:
    - postgres
    volumes:
    - ./:/app
    command: flask run --host 0.0.0.0
    environment:
    - FLASK_DEBUG=1
    - FLASK_ENV=development
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=mypassword
    volumes:
    - ./start-db.sql:/docker-entrypoint-initdb.d/start-db.sql
