version: "3.2"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    depends_on:
    - postgres
    volumes:
    - ./:/app
    - ./mocks:/tmp/nbgrader
    - ./pgdata
    environment:
    - FLASK_DEBUG=1
    - FLASK_ENV=development
    - DEBUG_METRICS=1 # https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#debug-mode
    - CANVAS_SSO_USERNAME=${CANVAS_SSO_USERNAME}
    - CANVAS_SSO_PASSWORD=${CANVAS_SSO_PASSWORD}
    - CANVAS_BASE_URL=${CANVAS_BASE_URL}
    - LTI_CONSUMER_KEY=${LTI_CONSUMER_KEY}
    - LTI_SHARED_SECRET=${LTI_SHARED_SECRET}
    - OAUTH2_ID=${OAUTH2_ID}
    - OAUTH2_KEY=${OAUTH2_KEY}
    - OAUTH2_URI=${OAUTH2_URI}
    - SELENIUM_OAUTH2_ID=${SELENIUM_OAUTH2_ID}
    - SELENIUM_OAUTH2_KEY=${SELENIUM_OAUTH2_KEY}
    - SELENIUM_OAUTH2_URI=${SELENIUM_OAUTH2_URI}
    - SECRET_KEY=${SECRET_KEY}
    - DATABASE_URI=${DATABASE_URI}
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=mypassword
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./scripts/start-db.sql:/docker-entrypoint-initdb.d/start-db.sql
    - ./pgdata:/var/lib/postgresql/data/pgdata
  selenium:
    image: selenium/standalone-chrome
    ports:
    - "4444:4444"
    shm_size: '2gb'
