# global
namespace: nb2canvas

# postgres secrets

# nb2canvas deployment
nb2canvas:
  name: web
  replicaCount: 1
  image: 
    repo: jdkindley/web_image
    tag: 1.0.8
  port: 5000
  nfs:
    server: 
    path: # volume mounts  


nfs:
  server: 
  path: 

# postgres deployment
postgres:
  name: db
  replicaCount: 1
  image: 
    repo: jdkindley/db_image
    tag: 1.0.1
  port: 5432

# tls secrets